[package]
name = "aio-plugin-hello-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dill = "0.15.0"
dioxus = { version = "=0.7.9", default-features = false, features = ["macro", "html"] }
az-dioxus-admin-shell = { git = "https://github.com/zjarlin/dioxus-admin-workbench.git", rev = "11c0d3856e541e3421854a2a96e995ba02546c3a", default-features = false }
az-ui-components = { git = "https://github.com/zjarlin/dioxus-admin-workbench.git", rev = "11c0d3856e541e3421854a2a96e995ba02546c3a" }

[lints]
workspace = true
